export const metadata = {
  title: "Wanderlust",
  description: "Generated by Next.js",
  icons: {
    icon: "/Compass.jpg",
  },
};
import "../styles/globals.css";

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
